plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.165'
    id 'org.spongepowered.mixin' version '0.7.32'
    id 'java'
}

apply from: file("common.gradle")

sourceSets {
    main.java { srcDirs += "/Forge/main/java" }
    main.resources { srcDirs += "/Forge/main/resources" }
}

repositories {
    maven { url "https://repo.spongepowered.org/maven" }

    flatDir { dirs "lib" }
}

dependencies {
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    implementation "net.neoforged:neoforge:${neoforge_version}"
}

jar {
    manifest { attributes(["MixinConfigs": "terraforged.mixins.json"]) }
}

mixin {
    add sourceSets.main, "terraforged.mixins.refmap.json"
}

minecraft {
    mappings channel: "official", version: minecraft_version
    runs {
        client {
            workingDirectory project.file("run")
            property "neoforge.logging.markers", "REGISTRIES"
            property "neoforge.logging.console.level", "debug"
            arg "-mixin.config=terraforged.mixins.json"
            jvmArgs "-Ddev"
            mods {
                terraforged {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file("run")
            property "neoforge.logging.markers", "REGISTRIES"
            property "neoforge.logging.console.level", "debug"
            arg "-mixin.config=terraforged.mixins.json"
            jvmArgs "-Ddev"
            mods {
                terraforged {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file("run")
            property "neoforge.logging.markers", "REGISTRIES"
            property "neoforge.logging.console.level", "debug"
            args "--mod", "terraforged", "--server", "--output", file("generated")
            arg "-mixin.config=terraforged.mixins.json"
            jvmArgs "-Ddatagen"
            mods {
                terraforged {
                    source sourceSets.main
                }
            }
        }
    }
}