modLoader="neoforge"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="terraforged"
displayName="TerraForged"
version="${file.jarVersion}"
authors="dags,Won-Ton"
credits="dags,Won-Ton"
logoFile="terraforged.png"
displayURL="https://terraforged.com"
issueTrackerURL="https://github.com/TerraForged/tracker/issues"
description="A terrain generator!"

[[mixins]]
config="terraforged.mixins.json"

[[dependencies.terraforged]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"
